name: RUN LABS

on: push

jobs:
  all-labs:
    runs-on: ubuntu-latest
    name: All labs
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.12'
      - name: requirements
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - run: echo "!!!!!!!!!! lab1 !!!!!!!!!!"
      - run: python ./lab1/main.py -A 1 -B 5 -C 6
      - run: python ./lab1/main.py -A 2 -B 2 -C 1
      - run: python ./lab1/main.py -A 1 -B 2 -C 1
      - run: echo "!!!!!!!!!! lab2 !!!!!!!!!!"
      - run: python ./lab2/main.py && python ./lab2/lib_test.py
      - run: echo "!!!!!!!!!! lab3 !!!!!!!!!!"
      - run: echo "~~~~~~~~~~ cm_timer ~~~~~~~~~~"
      - run: python ./lab3/cm_timer.py
      - run: echo "~~~~~~~~~~ field ~~~~~~~~~~"
      - run: python ./lab3/field.py
      - run: echo "~~~~~~~~~~ gen_random ~~~~~~~~~~"
      - run: python ./lab3/gen_random.py
      - run: echo "~~~~~~~~~~ print_result ~~~~~~~~~~"
      - run: python ./lab3/print_result.py
      - run: echo "~~~~~~~~~~ sort ~~~~~~~~~~"
      - run: python ./lab3/sort.py
      - run: echo "~~~~~~~~~~ unique ~~~~~~~~~~"
      - run: python ./lab3/unique.py
      - run: echo "~~~~~~~~~~ process_data ~~~~~~~~~~"
      - run: python ./lab3/process_data.py
